import "./globals.css";
import AuthProvider from "@/services/AuthProvider";
import LayoutWrapper from "../components/Shared/LayoutWrapper";
import Head from "next/head";
import { FollowingProvider } from "./context/FollowingContext";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Street Alpha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="antialiased" suppressHydrationWarning>
        <AuthProvider>
          <FollowingProvider>
            <LayoutWrapper>
              {children}
              <ToastContainer
                position="top-center"
                autoClose={2000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
            </LayoutWrapper>
          </FollowingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
