export const aboutData = [
  {
    id: 0,
    title: "Global Financial News",
    desc: "Stay ahead with real-time updates from markets around the world..",
    picture: "/assets/images/about/about_1.svg",
    isLabel: false,
  },
  {
    id: 1,
    title: "Financial Advisor",
    desc: "Your AI-powered companion for smarter, goal-based investing decisions.",
    picture: "/assets/images/about/about_2.svg",
    isLabel: false,
  },
  {
    id: 2,
    title: "Dashboard",
    desc: "Customizable overviews to track your portfolio, sectors, and strategies at a glance.",
    picture: "/assets/images/about/about_3.svg",
    isLabel: false,
  },
  {
    id: 3,
    title: "Data Visualizations",
    desc: "Make sense of market chaos with clean, interactive, and beautiful charts",
    picture: "/assets/images/about/about_4.svg",
    isLabel: false,
  },
  {
    id: 4,
    title: "Copilot",
    desc: "Let our intelligent assistant guide your financial moves, from insights to execution",
    picture: "/assets/images/about/about_5.svg",
    isLabel: true,
  },
  {
    id: 5,
    title: "Fundamentals",
    desc: "Dive deep into balance sheets, earnings, and key metrics that drive company value",
    picture: "/assets/images/about/about_6.svg",
    isLabel: false,
  },
  {
    id: 6,
    title: "Valuation and Estimates",
    desc: "See what the numbers say - from intrinsic value to analyst targets",
    picture: "/assets/images/about/about_7.svg",
    isLabel: true,
  },
  {
    id: 7,
    title: "Forecasts",
    desc: "Predictive models and trends to help you navigate what’s next in the markets",
    picture: "/assets/images/about/about_8.svg",
    isLabel: false,
  },
  {
    id: 8,
    title: "Hedge Funds",
    desc: "Track how the big players invest — and what their moves signal",
    picture: "/assets/images/about/about_9.svg",
    isLabel: true,
  },
];
