export const sliderData = [
  { id: 1, path: "/assets/images/company-logo/logo1.svg" },
  { id: 2, path: "/assets/images/company-logo/logo2.svg" },
  { id: 3, path: "/assets/images/company-logo/logo3.svg" },
  { id: 4, path: "/assets/images/company-logo/logo3.svg" },
  { id: 5, path: "/assets/images/company-logo/logo5.svg" },
  { id: 6, path: "/assets/images/company-logo/logo1.svg" },
  { id: 7, path: "/assets/images/company-logo/logo3.svg" },
  { id: 8, path: "/assets/images/company-logo/logo2.svg" },
  { id: 9, path: "/assets/images/company-logo/logo4.svg" },
  { id: 10, path: "/assets/images/company-logo/logo5.svg" },
  { id: 11, path: "/assets/images/company-logo/logo2.svg" },
  { id: 12, path: "/assets/images/company-logo/logo1.svg" },
  { id: 13, path: "/assets/images/company-logo/logo3.svg" },
  { id: 14, path: "/assets/images/company-logo/logo4.svg" },
  { id: 15, path: "/assets/images/company-logo/logo5.svg" },
  { id: 16, path: "/assets/images/company-logo/logo4.svg" },
  { id: 17, path: "/assets/images/company-logo/logo3.svg" },
  { id: 18, path: "/assets/images/company-logo/logo2.svg" },
  { id: 19, path: "/assets/images/company-logo/logo1.svg" },
  { id: 20, path: "/assets/images/company-logo/logo5.svg" },
];
