export const companyData = [
  {
    id: 1,
    name: "Apple",
    logo: "/assets/images/dashboard-company/apple.svg",
    isFollow: true,
  },
  {
    id: 2,
    name: "Microsoft",
    logo: "/assets/images/dashboard-company/microsoft.svg",
    isFollow: true,
  },
  {
    id: 3,
    name: "Nvidia",
    logo: "/assets/images/dashboard-company/nvidia.svg",
    isFollow: true,
  },
  {
    id: 4,
    name: "Amazon",
    logo: "/assets/images/dashboard-company/amazon.svg",
    isFollow: false,
  },
  {
    id: 5,
    name: "Intel",
    logo: "/assets/images/dashboard-company/intel.svg",
    isFollow: false,
  },
  {
    id: 6,
    name: "Alibaba",
    logo: "/assets/images/dashboard-company/alibaba.svg",
    isFollow: false,
  },
  {
    id: 7,
    name: "Baidu",
    logo: "/assets/images/dashboard-company/baidu.svg",
    isFollow: true,
  },
  {
    id: 8,
    name: "Tesla",
    logo: "/assets/images/dashboard-company/tesla.svg",
    isFollow: false,
  },
  {
    id: 9,
    name: "Apple",
    logo: "/assets/images/dashboard-company/apple.svg",
    isFollow: true,
  },
  {
    id: 10,
    name: "Microsoft",
    logo: "/assets/images/dashboard-company/microsoft.svg",
    isFollow: true,
  },
  {
    id: 11,
    name: "Nvidia",
    logo: "/assets/images/dashboard-company/nvidia.svg",
    isFollow: true,
  },
  {
    id: 12,
    name: "Amazon",
    logo: "/assets/images/dashboard-company/amazon.svg",
    isFollow: false,
  },
  {
    id: 13,
    name: "Intel",
    logo: "/assets/images/dashboard-company/intel.svg",
    isFollow: true,
  },
  {
    id: 14,
    name: "Alibaba",
    logo: "/assets/images/dashboard-company/alibaba.svg",
    isFollow: false,
  },
  {
    id: 15,
    name: "Baidu",
    logo: "/assets/images/dashboard-company/baidu.svg",
    isFollow: true,
  },
  {
    id: 16,
    name: "Tesla",
    logo: "/assets/images/dashboard-company/tesla.svg",
    isFollow: false,
  },
  {
    id: 17,
    name: "Apple",
    logo: "/assets/images/dashboard-company/apple.svg",
    isFollow: true,
  },
  {
    id: 18,
    name: "Microsoft",
    logo: "/assets/images/dashboard-company/microsoft.svg",
    isFollow: true,
  },
  {
    id: 19,
    name: "Nvidia",
    logo: "/assets/images/dashboard-company/nvidia.svg",
    isFollow: true,
  },
  {
    id: 20,
    name: "Amazon",
    logo: "/assets/images/dashboard-company/amazon.svg",
    isFollow: false,
  },
  {
    id: 21,
    name: "Intel",
    logo: "/assets/images/dashboard-company/intel.svg",
    isFollow: false,
  },
  {
    id: 22,
    name: "Alibaba",
    logo: "/assets/images/dashboard-company/alibaba.svg",
    isFollow: true,
  },
  {
    id: 23,
    name: "Baidu",
    logo: "/assets/images/dashboard-company/baidu.svg",
    isFollow: true,
  },
  {
    id: 24,
    name: "Tesla",
    logo: "/assets/images/dashboard-company/tesla.svg",
    isFollow: false,
  },
  {
    id: 25,
    name: "Apple",
    logo: "/assets/images/dashboard-company/apple.svg",
    isFollow: true,
  },
  {
    id: 26,
    name: "Microsoft",
    logo: "/assets/images/dashboard-company/microsoft.svg",
    isFollow: true,
  },
  {
    id: 27,
    name: "Nvidia",
    logo: "/assets/images/dashboard-company/nvidia.svg",
    isFollow: true,
  },
  {
    id: 28,
    name: "Amazon",
    logo: "/assets/images/dashboard-company/amazon.svg",
    isFollow: false,
  },
  {
    id: 29,
    name: "Intel",
    logo: "/assets/images/dashboard-company/intel.svg",
    isFollow: true,
  },
  {
    id: 30,
    name: "Alibaba",
    logo: "/assets/images/dashboard-company/alibaba.svg",
    isFollow: false,
  },
  {
    id: 31,
    name: "Baidu",
    logo: "/assets/images/dashboard-company/baidu.svg",
    isFollow: true,
  },
  {
    id: 32,
    name: "Tesla",
    logo: "/assets/images/dashboard-company/tesla.svg",
    isFollow: true,
  },
];
