export const globeConfig = {
  pointSize: 4,
  globeColor: "#ebecef",
  showAtmosphere: true,
  atmosphereColor: "#fff",
  atmosphereAltitude: 1,
  emissive: "#fcfcfc",
  emissiveIntensity: 1.8,
  shininess: 2,
  polygonColor: "#48495b",
  ambientLight: "#ffffff",
  directionalLeftLight: "#ffffff",
  directionalTopLight: "#ffffff",
  pointLight: "red",
  arcTime: 1000,
  arcLength: 0.9,
  rings: 1,
  maxRings: 3,
  initialPosition: { lat: 22.3193, lng: 114.1694 },
  autoRotate: true,
  autoRotateSpeed: 0.5,
};
