export const tableData = [
  {
    logo: "/assets/images/dashboard-company/alibaba.svg",
    shortName: "BABA",
    fullName: "Alibaba",
    lastPrice: 258.9,
    status: "Positive",
    fairValue: 249.75,
    return: 23,
    roic: 14,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/jd.svg",
    shortName: "JD",
    fullName: "jd.com",
    lastPrice: 258.9,
    status: "Negative",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/bidu.svg",
    shortName: "Bidu",
    fullName: "Baidu",
    lastPrice: 258.9,
    status: "Neutral",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/alibaba.svg",
    shortName: "BABA",
    fullName: "Alibaba",
    lastPrice: 258.9,
    status: "Positive",
    fairValue: 249.75,
    return: 21,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/alibaba.svg",
    shortName: "BABA",
    fullName: "Alibaba",
    lastPrice: 258.9,
    status: "Positive",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/alibaba.svg",
    shortName: "BABA",
    fullName: "Alibaba",
    lastPrice: 258.9,
    status: "Positive",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/jd.svg",
    shortName: "JD",
    fullName: "jd.com",
    lastPrice: 258.9,
    status: "Negative",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/bidu.svg",
    shortName: "Bidu",
    fullName: "Baidu",
    lastPrice: 258.9,
    status: "Neutral",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/alibaba.svg",
    shortName: "BABA",
    fullName: "Alibaba",
    lastPrice: 258.9,
    status: "Positive",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
  {
    logo: "/assets/images/dashboard-company/alibaba.svg",
    shortName: "BABA",
    fullName: "Alibaba",
    lastPrice: 258.9,
    status: "Negative",
    fairValue: 249.75,
    return: 23,
    roic: 15,
    pe: 18.5,
  },
];
